FROM golang:1.21.1

WORKDIR /ServerAmerica

COPY go.mod go.sum ./

RUN go mod download

COPY ServerAmerica/parametros_de_inicio.txt ./ServerAmerica/
COPY ServerAmerica/main.go ./

RUN go get github.com/MauricioCortesRo/Proto

RUN go build -o ServerAmerica_bin .

ENTRYPOINT [ "/ServerAmerica/ServerAmerica_bin" ]