FROM golang:1.21.1

WORKDIR /ServerAsia

COPY go.mod go.sum ./

RUN go mod download

COPY ServerAsia/parametros_de_inicio.txt ./ServerAsia/
COPY ServerAsia/main.go ./

RUN go get github.com/MauricioCortesRo/Proto

RUN go build -o ServerAsia_bin .

ENTRYPOINT [ "/ServerAsia/ServerAsia_bin" ]