FROM golang:1.21.1

WORKDIR /ServerOceania

COPY go.mod go.sum ./

RUN go mod download

COPY ServerOceania/parametros_de_inicio.txt ./ServerOceania/
COPY ServerOceania/main.go ./

RUN go get github.com/MauricioCortesRo/Proto

RUN go build -o ServerOceania_bin .

ENTRYPOINT [ "/ServerOceania/ServerOceania_bin" ]