FROM golang:1.21.1

WORKDIR /NameNode

COPY go.mod go.sum ./

RUN go mod download

COPY NameNode/DATA.txt ./NameNode
COPY NameNode/main.go ./

COPY NameNode/DATA.txt ./NameNode

RUN go get github.com/MauricioCortesRo/Lab2_Proto

RUN go build -o ServerOms_bin .

ENTRYPOINT [ "/NameNode/ServerOms_bin" ]
