FROM golang:1.21.1

WORKDIR /Europa

COPY go.mod go.sum ./

RUN go mod download

COPY Europa/names.txt ./
COPY Europa/main.go ./

RUN go get github.com/MauricioCortesRo/Lab2_Proto

RUN go build -o ServerEuropa_bin .

ENTRYPOINT [ "/Europa/ServerEuropa_bin" ]